### PR TITLE
Add `@hidden` tag

### PR DESCRIPTION
**Pull request by 3Rafal**
Needed for https://github.com/ocaml/odoc/pull/950

### CODE REVIEW

**Review by Julow — APPROVED** [review]
Looks good! You need to run `dune build @fmt` before it can be merged.

**Comment by 3Rafal** [comment]
@Julow , done :)

**Comment by Julow** [comment]
Thanks! Waiting on @jonludlam approval and merge.

**Comment by jonludlam** [comment]
Looks good thanks!

**Pull request merged**
